### ISSUE TITLE
Scrollbar instability due to activation of contents with incorrect size

### ISSUE THREAD

**Issue by flackr** [WICG/display-locking#109]
When the content-size of hidden content is not close to the real size, dragging the scrollbar is extremely unstable. Imagine a list of posts which when sized properly average 500px, but have the following markup:

```css
.post {
  render-subtree: invisible;
  min-height: 50px;
}
```
[live demo](https://flackr.github.io/virtual-scroller/demo/simple.html) viewable with `chrome --enable-blink-features=CSSRenderSubtree,DisplayLocking`

If you drag the scrollbar to a scroll position X, chrome will quickly do the following:
1. Scroll to X.
2. Hide items in old scroll position - with scroll anchoring scroll is now at position X - Y.
3. Scrollbar overall height is relatively unaffected, so the next mouse movement processed scrolls back to X, i.e. repeat.

Eventually this will stabilize on the scroll position where all of the items above the current scroll position have 50px height, but this results in a lot of jittering while scrolling.

This behavior can be observed at https://flackr.github.io/virtual-scroller/demo/simple.html (once github pages updates)

**Comment by flackr** [comment]
As for possible solutions, I have a few thoughts from simple to difficult:

1. Only track deltas in scrollbar dragging - after content changes size scroll relative to the new scroll position rather than back to where the mouse / finger is on the scrollbar track.

2. Have the scrollbar track a separate layout where all items are hidden. This means they would always assume the size of 50px for the purposes of the scrollbar track. This keeps the scrollbar position consistent but may require a lot of additional layout work.

3. Lock the scrollbar while dragging, update the scrollbar size only after the drag is complete. The scrollbar positions would need to map to the old positions of the content. This would result in inconsistent scrollbar scrolling velocity when items change size but for longer scrollers I suspect this wouldn't be noticeable. This also would make dragging scrollbars on infinite scrollers which autoload contents easier.

4. Implement element-based scroll track scrolling. Instead of trying to map scrolling to pixel offsets map scrolling to the element (and proportion of that element) having been scrolled by. Out of flow elements would need to be excluded.

**Comment by chrishtr** [comment]
I like option 1 and 4.

1 is good because it seems unlikely that users will be so sophisticated as to actually care that much about long scroll jumps being so "accurate".

4 is good because it seems to be bad UX design to have a UI element change out from under the developer. I don't know about the rest of the suggestion. Instead we can just have a fixed UI for it during a drag gesture, and interpret movings according to 1.

Option 1 doesn't sound too hard to implement; not sure about 4.

**Comment by vmpstr** [comment]
In 1, the scroll thumb would deviate from the mouse cursor which is a familiar effect but I don't really like it if we can avoid it.

In 4, it seems like it would look nice with the only downside that we don't really know what the scroll position represents on a page that has changed significantly since the scroll started.

Is 1 a breaking change for anything? Or can we just try doing that?

**Comment by flackr** [comment]
1 is not a breaking change - in fact it's what happens in Chrome when an infinite scroller adds content to the end of the document (e.g. try scrollbar dragging to the bottom on twitter). It just doesn't seem that we account for the scroll anchoring offset change.

**Comment by flackr** [comment]
I filed https://crbug.com/1043674 in chromium for making the same behavior happen for scroll anchoring as we do for the document growing (i.e. continuing to drag from the current scroll position) - i.e. option 1.

**Comment by fergald** [comment]
My own take on this is that the virtual scroller would be better off
allowing users to express sizes as part of the VS's API (e.g. with an
attribute that the VS looks at). The content-size only works at all because
we are locking the elements directly. If we move away from locking them
directly then and put them in slots (which we should do to stop the locking
being user-detectable and interferable) then the content-size will have no
impact at all.

Given a way to express expected heights, the VS then would set
content-sizes based on that (and the observed error) and hopefully lead to
a lot less jumping around.

We haven't really talked about what a sizing API would look like, mainly
because just getting the basics to work was hard enough.

>

**Comment by flackr** [comment]
I'm not sure I follow - setting content-size is the way to tell the browser the expected height while locked; however, if there's any error in the expected height then the scroll position will change when elements above the current scroll position are locked / unlocked to a different size. Option 1 above should prevent any jumping when such an error occurs - whether small or large.

As for slotting into a tree structure - you could set the content-size of the slot to be a sum over the children content sizes or # of children * some average expected size if the sizes were unknown.

**Comment by fergald** [comment]
There's 2 levels here.

1 the virtual scroller user, who needs a way to say that "I expect this div to be big and this one to be small"
2 the virtual scroller author, who needs to manage pixel sizes so that the scroll-bar is as close to accurate as possible even when most of the sizes are unknown

So `content-size` is the tool for 2. We currently have nothing for 1. If we had something 1 then 2 could do a much better job. We would still have jumps but assuming the scroller user has actually done a good job of getting the relative sizes right, the severity of the problem you are trying to fix is much less.

**Comment by flackr** [comment]
Ah I see! That sounds like an issue for https://github.com/WICG/virtual-scroller though, right? Since display locking on its doesn't seem to have enough information to turn the estimate from the user into a pixel size, where the virtual scroller could make a good estimate based on other items in the list.

**Comment by fergald** [comment]
Sorry, I actually thought this was in the VS repo. I didn't read it closely
enough.

**Comment by vmpstr** [comment]
Current plan: 
- @flackr fixed the chromium being unusable due to scroll thumb jittering immensely
- we have a tentative idea of how to fix the jitter by locking the scrollbar area when drag starts, need to explore implementation to see if that's easy to do.

**Comment by yisibl** [comment]
@flackr render-subtree renamed to subtree-visibility
