### ISSUE TITLE
beforematch: fragment link navigation is synchronous

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#135]
@josepharhar discovered that when we change the fragment link, the scroll offset changes immediately. This means that we can't fire `beforematch` first and scroll second. We have to do the scroll, otherwise we break the web. 

Is it still useful to include fragment link navigation in `beforematch`? This should not be an issue for find in page (timing is not script controlled) or scroll-to-text (only onload which isn't really script controlled)

I don't know if we should say "only on the load fragment link we fire `beforematch`, not any future fragment link changes". This, and in combination with the `hashchange` event, makes me think that perhaps we can just omit fragment link navigation from this.

Thoughts?
/cc @chrishtr

**Comment by domenic** [comment]
> This means that we can't fire beforematch first and scroll second. We have to do the scroll, otherwise we break the web.

I don't understand this conclusion. Couldn't we fire beforematch synchronously and then change the scroll offset?

**Comment by vmpstr** [comment]
We were really hoping to avoid running event handlers synchronously inside another script, so we were planning on running this at the beginning of the frame (before rAF handlers).

**Comment by domenic** [comment]
Hmm. This case feels like it'd be worth making an exception.

**Comment by vmpstr** [comment]
Yeah, I think that's really the only way to have fragment link beforematch things

Another possibility is that we update the scroll to where the element is, then at the frame time we run the event handlers and if the offset is different again then scroll again, but that's also feels like its going to break the web

**Comment by josepharhar** [comment]
Thanks for raising this issue vmpstr!
To elaborate on the initial issue, in order to make beforematch delay scroll on scroll to fragment id, we would have to make [this wpt](https://github.com/web-platform-tests/wpt/blob/090a00033d21867ea3b0940e8c932c1b63685841/html/browsers/browsing-the-web/scroll-to-fragid/003.html) go from this:
```javascript
test(function() {
  assert_equals(document.scrollingElement.scrollTop, 0);
  location.hash = "test";

  var scroll1 = document.scrollingElement.scrollTop;
  assert_true(scroll1 > 0);

  location.hash = "test1";
  var scroll2 = document.scrollingElement.scrollTop;
  assert_true(scroll2 > scroll1);

  location.hash = ""
});
```
to this:
```javascript
async_test(async t => {
  assert_equals(document.scrollingElement.scrollTop, 0);

  let scroll1;
  document.getElementById('test').addEventListener('beforematch', () => {
    requestAnimationFrame(t.step_func(() => {
      scroll1 = document.scrollingElement.scrollTop;
      assert_true(scroll1 > 0);
      location.hash = 'test1';
    }));
  });

  document.getElementById('test1').addEventListener('beforematch', () => {
    requestAnimationFrame(t.step_func_done(() => {
      const scroll2 = document.scrollingElement.scrollTop;
      assert_true(scroll2 > scroll1);
      location.hash = '';
    }));
  });

  location.hash = 'test';
});
```
which seems pretty web breaking. This is only one of the several WPTs that failed with my patch. Since ScrollToTextFragment and find in page seem much less web observable, I guess we don't have to worry about this particular issue as much for those.

Now about solutions:
> I don't understand this conclusion. Couldn't we fire beforematch synchronously and then change the scroll offset?

I initially tried to just fire the event right before we set the scroll offset, but that causes issues because the scroll offset tends to get updated in a particular step of the rendering pipeline where we aren't allowed to run script, if I understand correctly. I suppose I could look into this more... I mean, if we are in script, and we change location.hash, I imagine there has to be some way we can just fire the event synchronously before we return to the script that changed location.hash... but I guess if its really important that we run beforematch at that other step of the rendering pipeline, and we must return to the script that changed location.hash and draw another frame, then this wouldn't work.

 > Another possibility is that we update the scroll to where the element is, then at the frame time we run the event handlers and if the offset is different again then scroll again, but that also feels like its going to break the web

How do you feel like this is going to break the web? We would only scroll twice if beforematch actually changes something, right? So existing websites shouldn't notice anything different, right...?

**Comment by vmpstr** [comment]
> How do you feel like this is going to break the web? We would only scroll twice if beforematch actually changes something, right? So existing websites shouldn't notice anything different, right...?

I imagine that one could change the hash, read the scroll offset, then construct some sort a new element based on the scroll offset, insert it into the dom. Then by the time we run the next frame, layout has changed (image loaded, content changed, something other that beforematch) which changes the position of the scrolled element:
Previously: we're in a wrong scroll position with the right constructed element based on scroll offset
Now: we're in the right scroll position with the wrong constructed element based on scroll offset.

Is this a contrived example? Sure :) But it's a behavior change that does not depend on the site using `beforematch`, so by some definition that breaks the web.

**Comment by vmpstr** [comment]
Let's see if making this event synchronous (only for fragment navigation) will work. Are there any objections to this?

**Comment by josepharhar** [comment]
> Let's see if making this event synchronous (only for fragment navigation) will work. Are there any objections to this?

Sounds good to me, it sure seemed like the best way to avoid changing the synchronous scrolling behavior when script changes window.location.hash while still firing beforematch before the scrolling actually occurs.
This is the behavior i just shipped the prototype with.

**Comment by josepharhar** [comment]
I think this is pretty much taken care of at this point: we will fire it sync.

I was able to find a way to get around the issues I mentioned about not being able to run script synchronously by moving the event firing from right before scrolling to the constructor of ElementFragment. If this solution becomes problematic, hopefully there is another spot I can find to fire the event.
