### ISSUE TITLE
Spec clarification: scrollIntoView(), focus(), find-in-page scroll targets

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#139]
The current spec for `auto` says that the content should be not rendered when hidden (ie skipped element) but that it should be available for things like find-in-page.

Now, for example scrollIntoView(), focus() / user focus,  find-in-page and similar behaviors will scroll the element into view and, say, center it. The question is what exactly are we centering? Because of size containment and contain-intrinsic-size, our size of the locked element may be different from the size it is when on-screen, so there's several options:

1.  Force rendering _with_ element's size containment, scroll to the element's position as determined by the forced rendering
2. Force rendering _without_ element's size containment (presuming that it will be rendered anyway once in the viewport), scroll to the element's position as determined by this process.
3. Scroll to the locked element and let viewport intersection naturally render it
4. Something else?

There are some pros and cons for each of the approaches: 1. seems to do the most faithful thing for the current state: we scroll where we know the element _currently_ is. 2. seems to do the most faithful thing for the final expected state: we essentially remove size containment, force layout, and scroll the result, because we know we will remove size containment when the element is in the viewport. 3. doesn't force layouts, which is nice and it is the least complicated approach but probably yields somewhat unexpected results especially with large sections that are locked.

We should agree on what to do here, an write it in the spec (at least as a non-normative note)

**Comment by chrishtr** [comment]
Why would option 3 yield unexpected results? If you scroll the content onto the page then it should unskip and display, along with any adjacent content that is also now oscreen.

**Comment by vmpstr** [comment]
It's the least precise of the options. For example, consider a section that is 10000px tall with `subtree-visibility: auto`, the user does a find-in-page for the word `foo` that appears once somewhere in that section. What do we center? 3 dictates that we center the 10000px tall section, which will then render, which means that the text `foo` can actually be offscreen when that happens.

FWIW, with my implementor hat on, I am somewhat leaning towards that. I just want to make sure we understand and document the implication

**Comment by chrishtr** [comment]
> FWIW, with my implementor hat on, I am somewhat leaning towards that. I just want to make sure we understand and document the implication

that == option 3 right?

In all of the cases you gave, I think the browser is able to atomically scroll and re-render the content so that it is centered properly if it wanted to put in the extra work and CPU time. For example, if scrollIntoView() is called then the browser could do this:
a) first verify that the scroll will actually bring the element into view (via some simple geometry computations)
b) schedule an animation to apply the scroll offset, with a special mode where it will render the content as visible in that frame and then adjust the scroll offset to center it. Other adjacent content may come in later.

I agree that the implementation of (b) in this case will visually differ for one frame from what the result would be if it scrolled and then let the IntersectionObservers for the element ancestors of the scrollIntoView element run at the same time as other observers, which will result in one incorrect frame before it renders the right thing, as opposed to a partially-correct frame.

Another third option for a browser could be to implement step (b) as:
- schedule an animation
- in the animation, perform layout, then unskip subtree-visibility:auto elements, then run the lifecycle, then adjust for final scroll offset

My current feeling is that any of the three options above (just make sure to unskip and center the one element; unskip all nearby elements via a double layout; do nothing and have one bad frame) should be spec-compliant for browsers to choose in their implementation. I view it as a similar set of constraints to how async image decoding may or may not result in flashes of images on some browsers; avoiding the flashes is a quality-of-implementation issue, not a spec compliance one.

**Comment by vmpstr** [comment]
> that == option 3 right?

Yes, I should've clarified that I was only responding about option 3.


I think if we have to have a result of `scrollIntoView()` that is consistent across all browsers, which means it would have to be specified. Right now, the [existing spec for `scrollIntoView()`](https://drafts.csswg.org/cssom-view/#scroll-an-element-into-view) states that we take `getBoundingClientRect` of the target element and align that in some shape or form. By this reading, we have to force the rendering of the target element _while_ it's under `contain: size` skipped element. Then use that resulting rect to scroll the content into view. By scrolling it, it will enter the viewport range which means that we will render and paint it. The resulting layout after removing size containment is what we will ultimately see on screen.

The final step (step 8) of [scrollIntoView() algorithm](https://drafts.csswg.org/cssom-view/#dom-element-scrollintoview) also says
```
Optionally perform some other action that brings the element to the user’s attention.
```
If we can interpret that as being able to do another scroll, then we can certainly do that.

My overarching concern here is that if we don't explicitly clarify this, then we're kind of bound by the existing interpretation of other things (like scrollIntoView). Do you think that behavior (which I tried to describe above) is fine?

**Comment by chrishtr** [comment]
I see. For `scrollIntoView` I suggest we use the rendering with `contain:size` in that step. This should hopefully work well almost all of the time since we also have the scroll anchoring feature.

Developers can also control the feature with [scrollIntoViewOptions](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView); we could also add a new option in the future to account for non-skipped rendering state if that becomes important.

**Comment by vmpstr** [comment]
Ok, sounds good. I'll use that as a template for the rest of the scrolling-type functionality where applicable
