### ISSUE TITLE
[css-subtree-visibility-1] definition of 'subtree-visibility: auto' mandates flickering of ink overflowing descendants when scrolling

### ISSUE THREAD

**Issue by dbaron** [WICG/display-locking#147]
I believe the current definition of `subtree-visibility: auto` mandates flickering of ink overflowing descendants when scrolling the page.

In particular, the current [definition of `auto`](https://wicg.github.io/display-locking/index.html#subtree-visibility-auto) refers to a [definition of "off-screen"](https://wicg.github.io/display-locking/index.html#off-screen) that defines being off-screen in terms of the element's border box.

This means that when the element's border box is offscreen (and outside whatever the UA-specific margin is) but some of it descendants are still onscreen, then those descendants are *required* not to be painted.

This means that the spec requires that, when scrolling, those descendants flicker visible/invisible as a function of the border-box's position in the viewport.

This seems very bad from a user interface perspective (visible flickering) and also probably bad from a performance perspective (mandating repainting during scroll).

It seems like it would be desirable for these elements to be forced to have `contain: paint` (or at least the overflow-related aspects of `contain: paint`; the z-ordering aspects of it don't seem to be needed, and `contain: paint` could perhaps be divided in half).

(I realize, as @chrishtr pointed out to me, that changing the "border box" definition isn't possible, because the point of the feature is to allow deferring of layout work inside the subtree until it's close to being onscreen.)

**Comment by chrishtr** [comment]
> It seems like it would be desirable for these elements to be forced to have `contain: paint` (or at least the overflow-related aspects of `contain: paint`; the z-ordering aspects of it don't seem to be needed, and `contain: paint` could perhaps be divided in half).

By these elements, I think you mean ones with `subtree-visibility: auto` on them right? Even if `contain: paint` was added, the size of the element will change based on its subtree being skipped or not, since `contain:size` and `contain-intrinsic-size` are added and removed based on skipping.

Therefore, I think the flickering you describe is an unavoidable consequence of supporting responsive/flexible layouts and avoiding rendering work when content is offscreen, if the laid-out content of the subtree exceeds the border box of the `subtree-visibility: auto` element by more than the user-agent viewport margin.

Developers will have to know about this and plan their layouts accordingly. In addition, scroll anchoring will avoid layouts jumping around as a result of the skipping.

This might be a good argument for requiring a certain minimum margin though.

**Comment by dbaron** [comment]
> By these elements, I think you mean ones with `subtree-visibility: auto` on them right?

Yes.

> Even if `contain: paint` was added, the size of the element will change based on its subtree being skipped or not, since `contain:size` and `contain-intrinsic-size` are added and removed based on skipping.

Yes, this can still cause layout jumping.  But that's a very different effect from the paint flickering that I'm talking about.  I'm talking about paint flickering where an element sometimes paints and sometimes doesn't, regardless of its size changing or not.

**Comment by chrishtr** [comment]
> Yes, this can still cause layout jumping. But that's a very different effect from the paint flickering that I'm talking about.

Yes I know; was just pointing that out also in case it helped.

> I'm talking about paint flickering where an element sometimes paints and sometimes doesn't, regardless of its size changing or not.

Yes, this can happen if the subtree visual overflow exceeds the bounds of the user agent margin. I don't see how to avoid it.

**Comment by dbaron** [comment]
At a minimum, that seems like it might require standardizing the user agent margin, because of interoperability problems over this issue.

It still seems to me like requiring paint containment (or part of it) would avoid it.

**Comment by vmpstr** [comment]
#### Context for our current containment values:

We found that the current values of containment are the minimum set required for us to achieve good performance gains, by skipping rendering work:

(container here is defined as element with `subtree-visibility: auto`)

* `contain: layout` ensures that the layout of items in the container does not affect layout outside, meaning that we do not have to compute the layout values.
* `contain: style` ensures that the counters inside the container do not affect counters outside, so that we can skip styling elements inside.
* `contain: size` ensures that the elements within the container do not affect the container size itself, allowing us again to skip layout of the elements within

As a side note, size `layout` and `style` containment can change layout (e.g. margin collapsing doesn't happen across `layout` containment boundary), we decided that it is better to keep it present even if the content is rendered to avoid extra layout work and layout changes. We decided that we can't keep `size` containment simply because it significantly limits the types of responsive design sites that are possible (i.e. the container size can never depend on the descendant sizes)

#### Ink overflow:

Now, it's definitely possible for us to have ink overflow that's visible and disappears on the next frame in response to a scroll (although I think stating that the spec mandates flickering is a bit leading; it mandates we stop painting descendants).

(As an aside, I don't think there are any more performance implications here than without ink overflow, since contents would be painted or not painted in response to scrolls anyway -- this _might_ save raster time, but with browsers rasterizing content outside of the viewport, it is also unlikely)

We can solve this problem by adding `paint` containment. This containment would have to be at least present when the contents are painted. However, we gain no other benefit from this containment: we do not expose an opportunity for skipping any type of work when things are off-screen, since we already do not paint any descendant. The only thing we do is it prevents developers from making containers with ink overflow, ensuring things do not 'flicker', and limiting the usability of the feature for any kind of 'valid' ink overflow case (e.g. horizontal ink overflow in a vertical scroller). It is for this reason that I do not think we should add a requirement for `paint` containment. Although, developer documentation would probably benefit from having a section describing the gotchas of having containers with ink overflows and how to address them.

If it is the developers desire to prevent ink overflow and any such flickering, they are of course free to add `paint` containment to containers themselves, ensuring a good visual behavior. Note that this, again, is different from `layout` `style` and `size` containments, which _the browser_ requires to optimize work. `paint` containment is only a requirement for the _developer_ to ensure the users do not see any kind of flicker.

#### Interop:

Now, the important part here is browser interop, since this ink overflow can appear at different times depending on the user-agent specified margin. We should address this. I was hoping to leave the specifics to the user-agent, but perhaps we should specify precisely the margin that user-agents have to use (or perhaps at least the lower bound of the margin). In Chromium, since we are using an internal version of the intersection observer, we are using 50% of the viewport margin for this.

Note, however, that this has its own caveats: the intersection observer only considers margins on the root element, all other clippers between the observed element and the root are taken without margin. This means that if the 'subtree-visibility: auto'  element is just clipped by a scroller which is itself fully within the viewport, the element would be considered off-screen.

I don't think we want to tie this spec with the intersection observer spec, since determining whether things are off-screen can be done in other ways. So, I'm not too sure to what degree or how to specify exactly what margin should the user-agent use.

**Comment by heycam** [comment]
> The only thing we do is we prevent developers from making containers with ink overflow, ensuring things do not 'flicker', and limiting the usability of the feature for any kind of 'valid' ink overflow case (e.g. horizontal ink overflow in a vertical scroller).

To me it seems beneficial to design the feature so that authors cannot accidentally cause bad behavior like this ink overflow flickering.  I can imagine authors creating a virtual list with font that has some glyphs that have ink overflow, but during development they only use text that doesn't use those glyphs, so they don't notice the problem and think to add `contain: paint`.  Another concern would be that different browser engines could cause different ink overflow, just due to e.g. text layout being different, resulting in flickering occurring in one browser and not another.

If you have concrete examples of "valid" overflow in the opposing dimension that users of subtree-visibility would want to render that would help evaluate whether adding paint containment is reasonable.

**Comment by vmpstr** [comment]
> If you have concrete examples of "valid" overflow in the opposing dimension that users of subtree-visibility would want to render that would help evaluate whether adding paint containment is reasonable.

I'll admit that any example that I can come up with which has "valid" cross direction overflow can probably be dismissed as overly contrived.

> I can imagine authors creating a virtual list with font that has some glyphs that have ink overflow, but during development they only use text that doesn't use those glyphs, so they don't notice the problem and think to add `contain: paint`

In this example having automatic paint containment replaces the flickering issue with the fact that their glyphs will now be clipped (a bug that would also go unnoticed if that text is not used during development). This is not an improvement in my opinion, especially since this would be a problem for any ink overflow, no matter how small. Flickering would only happen if ink overflow exceeds whatever margin the browser has. Note also that there would be no way for the developer to opt-out of paint containment and ink overflow clipping, short of simply not using subtree-visibility. Flickering, on the other hand, can always be eliminated by developer specified paint containment (if the developer deems that to be a viable option for their content).

> Another concern would be that different browser engines could cause different ink overflow, just due to e.g. text layout being different, resulting in flickering occurring in one browser and not another.

The spirit of the `subtree-visibility: auto`, and specifically the viewport margin, is that the margin would be large enough to mitigate any type of browser differences that may cause small ink overflow differences. That is, it is not meant to be the case that the content is painted only very close to or in the viewport. It is meant to simply say that if it's far enough it is skipped, but if it's within say a viewport or two (or maybe less than, say, 1000px away), then it is not skipped. I admit that the current spec draft could use some at least non-normative text explaining ink overflow flickering problem, and encouraging implementors to have a "sufficiently large" margin.

Overall, I agree that there is work to be done here. I still don't think that adding paint containment is the correct course of action. Do you think specifying a better value for the margin, and adding non-normative text explaining why the margin is important, would address the concerns raised here. Or do you think paint containment is really the only way forward? Is there another option that we're missing?

**Comment by vmpstr** [comment]
We've had some more discussions on the topic. Here is another proposal for moving forward:

I think that it is important for developers to be able to have ink overflow while using `subtree-visibility`. However, it is also important for us to not have ink overflow flickering as a result (especially if that's an interop issue). So, our current proposal is that we would like to do two things:
1. Add `contain: paint` as a containment requirement when `subtree-visibility` is present with any value other than `visible`.
2. Propose an additional feature, tentatively `contain-paint-margin`, which inflates the ink overflow clip added by paint containment by the specified margin (positive px; default is 0).

This makes the feature _safe by default_, in that with the minimum usage of subtree-visibility, paint containment prevents any ink overflow flickering. At the same time, it allows the developer to expand the bounds of the paint containment clip to allow for some ink overflow. The user-agents can then use the contain-paint-margin in combination with the element's bounding box to determine whether they have to start rendering the element.

Does this sound reasonable? Specifically, would you be generally in favor of a feature like `contain-paint-margin`, which would be proposed independently of `subtree-visibility`?

**Comment by dbaron** [comment]
It sounds pretty reasonable to me.

I'd note that it sounds pretty similar to the original design of the `clip` property in CSS 2.0 (which wasn't implemented and had to be revised for compat in CSS 2.1) in which it was originally tied to `overflow`.  I suspect reusing `clip` doesn't work, though.
