### ISSUE TITLE
Handle abort scenarios

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#28]
Examples:

1. Developer removes contain: contents value while locked.
2. Callback code throws an exception.

In these cases we should probably synchronously commit the lock and reject the promise.

**Comment by vmpstr** [comment]
Sounds reasonable. 2 is a definite yes, we should reject the promise. 

1. I guess we mean to say that if the value changes in a way that leaks layout overflow? In other words, there should be nothing wrong going from contain: content to contain: strict for example

**Comment by vmpstr** [comment]
With mode 2, it's an interesting question:

Before we append the element to the DOM we can't actually know if it would have containment when inserted, since its style may depend on the position it's in.

After we insert it, and we have callbacks pending, those callbacks may somehow cause us to gain containment... Like a callback could potentially modify DOM outside of the locked subtree. Does that means that we should run all callbacks first?

Finally, if we actually reach the stage when we begin commit, we first have to compute style before we can figure out whether the element has containment. Once that's done, this is the first spot where we can reliably reject if the element has no containment.

Does that sound like what you had in mind as well?

**Comment by chrishtr** [comment]
I hadn't though it through as carefully as that, but agree that this is the first place we can reliably
reject.

One additional reason I think it's necessary to reject in this case is that we need to signal
to the developer that this commit cannot be undone/re-locked.
