### ISSUE TITLE
Explicit commit

### ISSUE THREAD

**Issue by thysultan** [WICG/display-locking#31]
Is there any reason why this is the default.

>In this example, after the callback runs the lock is automatically committed.

Might this prevent use cases where i 1. You don't pass a callback to `acquireDisplayLock` and 2. Don't invoke `acquire` For example:

```js
const lock = element.acquireDisplayLock()
setTimeout(() => {
lock.commit() // no-op if someone else with the lock has already committed it.
}, 1000)

element.setAttribute('foo', 'bar')
element.appendChild(child)
```

How does the current behavior know when "all pending tasks are done".

**Comment by vmpstr** [comment]
Since the only way to schedule more callbacks is via acquireDisplayLock or the context that is passed there, the implementation can keep track of whether more tasks are scheduled. You're right that mutations outside of the lock/context can be scheduled but they will not cause the lock to not commit (ie it's not intended to be used in that way).

As for your first question, the reason this is default behavior is to better align with things like weblocks (see #15 ), it's "safe by default". In other words, if the developer forgets to do anything like commit, then the lock will automatically commit. The alternative is if the dev forgets to commit, the element will be forever locked.

I hope this explains the rationale.

**Comment by thysultan** [comment]
If possible how would one mimic the above example with the current semantics.

**Comment by vmpstr** [comment]
So there's a few options depending on what the desired effect is:

1.
element.acquireDisplayLock((context) => {
  element.setAttribute('foo', 'bar');
  element.appendChild(child);
});

2.
let resume_handle;
element.acquireDisplayLock((context) => {
  element.setAttribute('foo', 'bar');
  element.appendChild(child);
  resume_handle = context.suspend();
});
setTimeout(() => { resume_handle.resume(); }, 1000);

In 1, the element is modified and the lock is automatically committed
In 2, the commit is delayed until 1000 timer fires, which is when the lock is committed.

If the intent is to have it be forced after 1000 ms, then there will be a way of doing this but the details of the API are still not worked out, but it will be something along the lines of

let force_handle;
element.acquireDisplayLock((context) => {
  element.setAttribute('foo', 'bar');
  element.appendChild(child);
  force_handle = context.getForceHandle();
});
setTimeout(() => { force_handle.forceCommit(); }, 1000);

The intent is to have the lock commit "naturally" but also have a way to force it to be synchronous. (Note that in this last example, the API is still not really decided on, so naming can change but the overall sense of the example should still hold)

**Comment by thysultan** [comment]
Would the following still work?

```js
let resume_handle;
element.acquireDisplayLock((context) => {
  resume_handle = context.suspend();
});
setTimeout(() => { resume_handle.resume(); }, 1000);
element.setAttribute('foo', 'bar');
element.appendChild(child);
```

My main issue with the current implied semantics is that it's not feasible to assume DOM mutation can always happen within the `acquireDisplayLock` callback, given that it is more common for the abstraction that handles DOM mutation in most frameworks to be agnostic to the scheduling abstraction, which is where display locking is most useful.

**Comment by vmpstr** [comment]
Yes, this certainly would work as you would expect: it will keep the element locked until the resume is called. You can even do a similar thing to what you said before:

```js
let resume_handle;
element.acquireDisplayLock((context) => {
  resume_handle = context.suspend();
});
setTimeout(() => { resume_handle.resume(); }, 1000);
element.setAttribute('foo', 'bar');
element.appendChild(child);
...
resume_handle.resume(); // may happen first or second
```

there are two resume() calls here, and the first one will cause the lock to be committed, the second one is a no-op.

**Comment by vmpstr** [comment]
Just to note here, although the lock is acquired when the function is called. The callback does not necessarily run immediately, meaning that the resume_handle may or may not exist yet... That's why it's preferred that the dom changes happen in the callback. However, if it doesn't exist, you can set some boolean saying that the lock shouldn't suspend and check that in the callback to ensure that you don't suspend if you already want to commit. It's not the cleanest approach, but works.

**Comment by thysultan** [comment]
That is where my concerns stem from, the callback pattern makes it appear as though you can only guaranteed that a lock is active after the callback is invoked. Which can happen at some unknown time.

This greatly reduces the ergonomics of the API for frameworks.

My use case is that i want to be able to initialize a lock in a suspended state immediately after which i can have the guarantee that the lock is in effect and later resume the lock to flush/commit at my choosing.

**Comment by vmpstr** [comment]
Yeah I understand. FWIW the lock is in effect after the call to acquireDisplayLock it's just whether or not it's suspended depends on whether the callback has run. To elaborate on my previous comment, the not-so-clean way of accomplishing it would be something like this:

```js
let should_suspend = true;
let resume_handle;
...
function resumeIfNeeded() {
  should_suspend = false;
  if (resume_handle)
   resume_handle.resume();
}

element.acquireDisplayLock((context) => {
  if (should_suspend)
    resume_handle = context.suspend();
});

setTimeout(() => { resumeIfNeeded(); }, 1000);
// modify the element in whatever way
...
resumeIfNeeded();
```

The cost of this is an extra bool tracking which isn't ideal...

On a tangent, display locking also provides co-operative style/layout/paint processing, and I think that it's an equally valuable part of this.. so a pattern of where you build up your DOM without connecting it to the document and then calling

element.acquireDisplayLock((context) => { document.body.appendChild(context.lockedElement); });

is still valuable. This pattern becomes a bit more clunky if we have an explicit lock handle which we call commit on (on top of being easy to unintentionally permanently lock an element)

**Comment by thysultan** [comment]
>so a pattern of where you build up your DOM without connecting it to the document and then calling...

Frameworks can already handle the case for nodes that are not yet connected today without locks. That is they can just delay connecting the to the document since they are in full control of this. The more probably pattern is when the node is already connected to the document. 

Theoretically this is also possible when the node is connected but there is ultimately more hoops to jump through to get right.

Introducing the same hoops in a native display locking API doesn't make the API more attractive than the current status-quo.

Regarding the example: Since the lock is not in a suspended state can you still guarantee that the following mutation will be locked?

```js
...
setTimeout(() => { resumeIfNeeded(); }, 1000);
// modify the element in whatever way(this)
```

**Comment by vmpstr** [comment]
> Frameworks can already handle the case for nodes that are not yet connected today without locks. That is they can just delay connecting the to the document since they are in full control of this. The more probably pattern is when the node is already connected to the document.

That's true, but once inserted into the document, frameworks have no control of how much work will be done before the contents appear on screen (ie if it takes 10 frames to lay things out and paint them, then the page will do 10 frames of work synchronously). Display locking can yield in layout/paint allowing unrelated page elements to continue to be updated without the 10 frame delay. In other words it makes the append be more-or-less asynchronous.

> Regarding the example: Since the lock is not in a suspended state can you still guarantee that the following mutation will be locked?

Yes, there's a distinction between the lock being acquired and it being suspended. The lock is acquired at the time acquireDisplayLock() itself is run (not the callback), which means any mutations that follow act on a locked element. Suspend is only a way to extend the lifetime of a lock that would otherwise commit. Ie if you finish all of your mutations before the callback runs, then two things are true: 1. the mutations modified a locked element and 2. you don't need to suspend in the callback, the commit will happen 'naturally'

**Comment by thysultan** [comment]
>That's true, but once inserted into the document, frameworks have no control of how much work

If the framework is handling scheduling this is expected to happen, and to happen synchronously when the framework is ready to flush the work(connect it to the DOM). The most attractive case is what i believe to be the cases surrounding elements already connected to the DOM.

>1. the mutations modified a locked element 2. you don't need to suspend in the callback, the commit will happen 'naturally'.

Is there any reason why `.suspend()` is part of the context object passed to the callback instead of the lock object itself. This would otherwise solve my use case effortlessly. i.e:

```js
lock = element.acquireDisplayLock(noop)
lock.suspend()
setTimeout(() => { resume(); }, 1000)
// modify the element in whatever way
```

**Comment by vmpstr** [comment]
The primary reason for why "the lock" is in the context is that it is a misuse of the API to capture/use the context outside of the callback. The context provides other functionality such as schedule(), which should only be invoked from the callback in order to simplify the implementation of the feature (ie internally we need to keep track if any new schedules are at all possible, which is difficult if the context is available to arbitrary script).

That being said, we can provide a context to the callback and possibly have an object returned that can be used to suspend the lock (ie it would provide limited functionality: suspend/resume and maybe force synchronous commit). This would be some sort of a control object rather than "the lock" itself

@chrshtr wdyt

**Comment by thysultan** [comment]
>This is an interesting discussion point in and of itself. Are you a framework author? Could you share with us a specific use-case you have in mind?

Exhibit A: When one does initiate a lock you may intentionally not want it to commit automatically when JavaScript yields back to the browser process, instead you may want it to immediately transition to a suspend state because there maybe more work to enqueue within the next process. When the browser does yield back to us again we might resume if and when we are sure that all the commits within the subtree have been collected to insure they are processed in one batch instead of smaller chunks.

Maybe context can extend lock in someway akin to the following:

```
interface Context extends Lock {context specific methods}
interface Lock {suspend, resume, etc...}
```

**Comment by vmpstr** [comment]
> The lock is in general acquired asynchronously, which is important for setting up a lock on content already within the document (e.g. caching display lists,
> and computing stye to see if locking is allowed).

You're right. For mode 2 it can be acquired immediately. For mode 1, it depends on our decision of what to do with pixels. If we show stale pixels, then it's at least a lifecycle update to cache those..

**Comment by chrishtr** [comment]
> I can't see many use cases where this would be more ergonomic that synchronous acquisition.

It's not about ergonomics. If the DOM tree is dirty at the time the lock is acquired, a rendering frame must be generated to get the DOM into a consistent rendering state for the lock.

> For one i can already tell that this won't save an author from the ceremony of having to at-least partially re-implement a lock-like abstraction in a scheduler.

Can you give an example to explain what you are saying here?

**Comment by thysultan** [comment]
>If the DOM tree is dirty at the time the lock is acquired, a rendering frame must be generated to get the DOM into a consistent rendering state for the lock.

These intermediate commits that happen before JavaScript yields back to the browser should also get flushed after the lock is released.

>Can you give an example to explain what you are saying here?

For example: at a certain interval a scheduler could decide to lock a subtree. However other parts(the parts that mutate the DOM) of the framework may not need to know of this signal, and could continue processing updates as usual. Unless the lock is acquired immediately all these updates will at best bypass the lock given it doesn't yet exist or at worst bypass some. The scheduler at some point would release the lock of the subtree, and in doing so archiving the desired result of flushing commits in a single batch/frame in an attempt to avoid interleaved commits escaping the lock.

Since the current semantics do not support the above use-case, to both archive and avoid this you would still need to re-implement locks in JavaScript if the acquisition of the lock is not immediate/deterministic.

**Comment by vmpstr** [comment]
I think this is obsolete both in display locking and in rendersubtree versions.
