### ISSUE TITLE
Interaction with Shadow DOM

### ISSUE THREAD

**Issue by lilles** [WICG/display-locking#32]
The spec will need to be explicit about which trees it's talking about and how it interacts with Shadow DOM and slot changes.

Style inheritance and layout trees follow the flat tree order, which means for this case:
```
<div id="host"><span slot="x"></span></div>
<script>
  const root = host.attachShadow({mode:"open"});
  root.innerHTML = "<div><span><slot name='x' /></span></div>"
  root.querySelector("span").acquireDisplayLock();
</script>
```
The span child of the host is also locked for style/layout/paint updates?

Or put another way, it is the flat-tree subtree that is locked?

How will slot assignment changes like removing the slot attribute of the host child above affect locking?

**Comment by vmpstr** [comment]
I think this is also an issue with rendersubtree, since it can be specified in light dom but then slotted elsewhere. 

FWIW, I believe we're sticking with flat tree order here. IOW it's the element's subtree in the flat tree that has its rendering affected. We do need to document this and probably mention it in the spec.

**Comment by chrishtr** [comment]
We should specify flat tree descendants. I'll make sure to edit my HTML PR to match.

**Comment by vmpstr** [comment]
This was done to specify flat tree

**Comment by lilles** [comment]
Do we have test coverage for this?

**Comment by vmpstr** [comment]
Yes, we have some shadow DOM tests, I think https://cs.chromium.org/chromium/src/third_party/blink/web_tests/wpt_internal/display-lock/css-subtree-visibility/subtree-visibility-046.html this one specifically covers the fact that we are using a flat tree. We will of course be moving this to external/wpt when we get closer to agreement.

Also, we can always add more tests, so that's an ongoing item :)
