### ISSUE TITLE
Concern about activation and incremental search

### ISSUE THREAD

**Issue by marijnh** [WICG/display-locking#51]
It seems that all locked nodes that contain the search string are activated when searching. Since browser search is incremental, this has the unfortunate side effect that if:

 - You've rendered a code editor with a huge document inside of it using many chunks of hidden content for the off-screen parts
 - The user starts a text search and types, say, "e"

Most of the chunks will contain an "e", and will be activated, forcing the browser to render potentially hundreds of thousands of lines of content right away, largely defeating the point of the optimization.

Is there a solution to this yet?

**Comment by rakina** [comment]
So, we don't actually activate everything that matches the find-in-page, instead, we only activate the *main* match. The main match is the match that is specially highlighted, the one the browser scrolls to, the x-th match where your find-in-page bar shows `x/y` matches, we can navigate to the previous/next match to change the main match, and there's only one at any given point.

So, when we do find-in-page, we'll calculate the style values for all locked elements (and this is optimized in Chrome to only work on a few parts at a time and only on idle time), but only activate one match.

The reason is we don't actually need to notify other matches.
* If they're outside the viewport, we don't need to render them.
* If they are inside the viewport, they are either already in the viewport previously and are unlocked, or they are located near the main/active match, which got scrolled-to. In this case the web author should know through the `beforeactivate` event and they can commit() these nearby elements accordingly.

What do you think about the model? Maybe it makes more sense to also activate the locked elements near the main match too, if they're going to be part of the viewport? Maybe there should be two modes?

**Comment by marijnh** [comment]
Oh, that makes sense, thanks! I thought I saw different behavior, but I guess my test was flaky.

> Maybe it makes more sense to also activate the locked elements near the main match too, if they're going to be part of the viewport?

That wouldn't be strictly necessary for my use case—I'd need to handle the beforeactivate event and swap out the minimal representation of the content with a fully rendered one around the new viewport anyway (since the locked stuff is basically just there for search functionality, it'd be a very simple flat DOM without syntax highlighting and such applied).

**Comment by chrishtr** [comment]
What about the selection highlight for matches that are not the one selected? e.g. if I activate a search in Chrome on this github issue page, and type "the", there is one active match in orange, and a whole lot of other ones which receive a selection highlight in yellow. To make this work, activation will have to detect which matches are in a locked subtree which are on-screen, which requires computing some geometry for all locked roots. Is this in your plan also Rakina?

**Comment by rakina** [comment]
Matches other than the main match won't get activated. With the current design, it is the web author's responsibility to determine whether or not they should unlock locked elements (which may or may not contain matches) that are located near the main match when they get the `beforeactivate` event.

**Comment by chrishtr** [comment]
Ok.

**Comment by marijnh** [comment]
So does that mean the scrollbar markers will simply not be drawn for matches in locked (but not activated) subtrees?

**Comment by rakina** [comment]
> So does that mean the scrollbar markers will simply not be drawn for matches in locked (but not activated) subtrees?

They are still drawn. The scrollbar markers are drawn at/around the same time as the corresponding match is counted in the total matches, using the already-calculated style & layout values.

A bit of Blink impl detail on find-in-page: With some changes in the layout code we probably can do find-in-page by calculating just the style (not layout) values, but that would mean we won't get correct position data for the scrollbar tickmarks. At that point maybe matches in locked subtree can have "estimated" scrollbar tickmarks (word index per total word count maybe?)
