### ISSUE TITLE
Does selection activate locked elements?

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#57]
What should activatable locks do when being selected? Either drag select or ctrl-a

Argument for "unlock": does what user expects
Argument for "unlock only on-screen content": performs well

We could unlock everything since if the user is trying to copy all of the page (formatted) text, then we need to have it all unlocked. This also means we should reject an activatable acquire if the element is selected.

/cc @chrishtr @fergald @rakina

**Comment by rakina** [comment]
I think "unlock only on-screen content" is pretty hard to define/spec correctly, and AFAICT things like screen readers will read everything that's selected - so we probably would want to unlock everything in that case.

**Comment by vmpstr** [comment]
resolved: selection activates.

**Comment by rakina** [comment]
@xiaochengh brought up some cases where we want other activation (focus, find-in-page, etc) but not selection, such as the case of collapsed elements, tabbed ui, etc. I think this can be solved with adding `user-select:none;` on those elements so that it won't be selectable and won't get activated through selection. @xiaochengh, do you think it's enough?

**Comment by fergald** [comment]
A couple of problems I see with `user-select:none`

- the author needs to remember to add it or weird things happen
- more importantly the author needs to remember to take it off

I think we should think about this in terms of uses cases and when/where select-to-activate makes sense and I think that closesly aligns with performance vs non-performance uses of locking.

When content is conceptually rendered but locked for performance reasons, e.g. scroller, then select to activate makes sense.

When content is intentionally not rendered and requires some change in state to cause it render (e.g. expanding a zippy, clicking on a new tab), then it probably doesn't make sense (but find-to-activate does).

Maybe it's not a coincidence that these correspond to when scroll-to-activate makes sense too.

If we think being locked without a size is the right signal for whether scroll-to-activate makes sense then maybe the same thing applies to select however I worry that other scroller implementations could lock things without sizes because they are managing the elements so this seems like an unreliable indicator.

So maybe we should have a clearer semantic distinction between these states. It makes me think that an element can be in the DOM and
- not in the "document": invisible, unfindable, unselectable
- in the docment but hidden: findable, unselectable, not activated by scrolling
- in the document but optimized for performance: findable, selectable, activated by scrolling

**Comment by xiaochengh** [comment]
Thanks for bringing this up!

It makes more sense to me that performance optimization and intentional hiding are different use cases, and hence, are supported with different semantics and activation mechanisms.
