### ISSUE TITLE
Spec ResizeObserver and IntersectionObserver interactions.

### ISSUE THREAD

**Issue by fergald** [WICG/display-locking#71]
2 approaches seem possible

1 when invisible, observers stop triggering, when the observed element becomes visible again, it's size is compared to it's previously visible size.
2 when invisible, observers continue to trigger and anything which results in a layout of the observed element may trigger the observer

Number 1 reduces spurious work but probably requires us to save the pre-invisible size somewhere (and I don't think that somewhere currently exists).
Number 2 is simpler but could cause expensive work to be done pointlessly on invisible elements.

**Comment by fergald** [comment]
What do you mean leave them alone? Which of 1 or 2 are going to be the behaviours? Or do you mean there's a 3 - locking/unlocking never triggers a resize observer?

**Comment by chrishtr** [comment]
I'm saying that in cases when rendering is updated, `ResizeObserver`s should run. If rendering is not run, they don't. Therefore while invisible, `ResizeObserver` should not run.

I discussed `updateRendering` with @vmpstr  and @szager-chromium just now. If `updateRendering` is called, then we concluded `ResizeObserver`s should *not* run, mainly because we don't want the timing of `updateRendering` work to be observable by script. But the performance side-effect you mentioned is another win. If a developer wants to do `updateRendering` and have `ResizeObserver`-like behavior, they call it, then inspect layout and make any necessary changes, then call `updateRendering` again.

**Comment by fergald** [comment]
That's fine, as long as the following scenario does not occur

1 element gets locked
2 element changes size but no resize because it's locked
3 element gets unlocked with same size as #2, so no resize

Because now the element has changed size and never fired the observer.

**Comment by chrishtr** [comment]
> 3 element gets unlocked with same size as #2, so no resize

I agree that in this step the resize observer should fire. This will require some dirty bits in the implementation, but it is doable.

**Comment by chrishtr** [comment]
Implemented here.

https://chromium-review.googlesource.com/c/chromium/src/+/1860597

Will be able to close once we update the spec.
