### ISSUE TITLE
Should pseudo elements of a locked element get rendered?

### ISSUE THREAD

**Issue by rakina** [WICG/display-locking#77]
Most pseudo elements takes care of things in the element's subtree anyways (`::part, ::first-letter`, etc). But what about things like `::backdrop`? Or `::before` and `::after`?

**Comment by vmpstr** [comment]
Naively I'd say we don't paint those, since things like ::before is usually used to specify some content, right? That's kind of like a child. Is it technically part of the element itself?

/cc @chrishtr

**Comment by thysultan** [comment]
It should like `display:none;` follow the same status.

**Comment by chrishtr** [comment]
Not rendering any of them is the most performant, so let's go with that as a first choice.

However, we might need to adjust that if we find use cases where it makes a lot of sense to render them.

**Comment by tabatkins** [comment]
Def not render. They're child boxes, and all the children don't render.

**Comment by rakina** [comment]
Alright, resolving this then.

**Comment by vmpstr** [comment]
Reopening due to discussion at a sync-up

The feeling is that box decorations are drawn, so :before and :after should also draw since it's kind of close in spirit to being box decorations. Tab, you mentioned they definitely should not. But are they children in the DOM tree or layout tree? and what tree are we talking about when we say subtree should be invisible?

/cc @chrishtr @fergald @tabatkins

**Comment by vmpstr** [comment]
Closing again due to inactivity. As we spec it right now, we don't paint child boxes. If there's desire to do so, we can revisit in the future.
