### ISSUE TITLE
Should scrolling/viewport intersection activate/unlock locked elements?

### ISSUE THREAD

**Issue by rakina** [WICG/display-locking#79]
@chrishtr mentioned that this was brought up by some people during TPAC last week. Currently scrolling to/near a locked element such that it's in the viewport (but not through calling `scrollIntoView`) on it won't trigger activation/unlock the element, but maybe we should consider adding them so that the API is easier to use - no need to add intersection observers, etc. to detect that a locked element is near the viewport.

We (@chrishtr @vmpstr @fergald) discussed this earlier, we agree this might be useful to add, but are unsure if this should be grouped together with other activation cases or not:

* We need to observe the intersection between *every* locked element and the viewport, so this might be expensive if you have a large amount of locked elements. [virtual-scroller](https://github.com/WICG/virtual-scroller) has an optimization where it only observes elements that are close to the viewport, but it has a set of constraint (e.g. DOM order = visual order) that makes that possible while the browser needs to work in all cases - thus it has no other choice than to observe all locked elements.

* There are some cases where we want contents of a locked element to be findable, focusable, etc. but not activated-on-scroll/viewport-intersection. Cases include making a tabbed UI, carousel, etc.

* Activation through other means are instant/synchronous: focusing on a locked element will immediately unlock it, navigating to a linked locked element will also unlock it, etc. However, viewport intersection will use the same mechanism as IntersectionObserver, which is asynchronous. This gets more complicated/delayed when there are nested locked elements.

There might be other points that I missed, feel free to add to this thread!

**Comment by vmpstr** [comment]
> but it has a set of constraint (e.g. DOM order = visual order)

I've also talked with @flackr about this, and maybe having an ability to enforce dom order = visual order instead of virtual-scroller simply not working correctly if this is violated. Maybe something like preventing breaks in virtual scroller + script on items to somehow enforce correct order?

> There are some cases where we want contents of a locked element to be findable, focusable, etc. but not activated-on-scroll/viewport-intersection. Cases include making a tabbed UI, carousel, etc.

If we don't activate height=0 elements on scroll, maybe this is doable. I'm unsure how find in page works if the text it finds is clipped out? @rakina, do you know? Does it simply not find it? We should test to see at least

> This gets more complicated/delayed when there are nested locked elements.

My current thinking is to basically spec activation as asynchronous, with possibly some exceptions

**Comment by flackr** [comment]
> > but it has a set of constraint (e.g. DOM order = visual order)
> 
> I've also talked with @flackr about this, and maybe having an ability to enforce dom order = visual order instead of virtual-scroller simply not working correctly if this is violated. Maybe something like preventing breaks in virtual scroller + script on items to somehow enforce correct order?

I still think there's a lot of value to implicitly activating content that we think will be seen, however yes for the purposes of keeping the virtual scroller efficient I thought that we might have some style which enforces the ordering in a browser detectable way so that it can optimize runs of elements.

e.g.
```css
virtual-scroller {
  break-inside: avoid;
}

virtual-scroller > * {
  position: static !important; /* Maybe builtin !important could override site styles? */
  margin: 0 !important;
  contain: style layout paint;
}
```

Or we could have a new property which removes any ability to position children out of flow.

> > There are some cases where we want contents of a locked element to be findable, focusable, etc. but not activated-on-scroll/viewport-intersection. Cases include making a tabbed UI, carousel, etc.
> 
> If we don't activate height=0 elements on scroll, maybe this is doable. I'm unsure how find in page works if the text it finds is clipped out? @rakina, do you know? Does it simply not find it? We should test to see at least

I made a simple demo, and the most recent Chrome, Firefox, and Edge find text in clipped nodes, while Safari does not: https://output.jsbin.com/pitihuk/quiet. I haven't looked more into what specific conditions affect this.

> > This gets more complicated/delayed when there are nested locked elements.
> 
> My current thinking is to basically spec activation as asynchronous, with possibly some exceptions

I think this makes sense, presumably it is okay if the activation is synchronous since it will still be activated by the next update? Or would it have to be async?

**Comment by chrishtr** [comment]
> I still think there's a lot of value to implicitly activating content that we think will be seen, however yes for the purposes of keeping the virtual scroller efficient I thought that we might have some style which enforces the ordering in a browser detectable way so that it can optimize runs of elements.

If we can achieve that it would be great. Or the browser could simply optimize for subtrees which don't have out-of-flow positioned elements.

> I made a simple demo, and the most recent Chrome, Firefox, and Edge find text in clipped nodes, while Safari does not: https://output.jsbin.com/pitihuk/quiet. I haven't looked more into what specific conditions affect this.

We would ideally just change this behavior to not match. However this is hard because it requires layout...

**Comment by fergald** [comment]
I posted a longish reply over here https://github.com/WICG/display-locking/issues/57#issuecomment-535297465 earlier. I think selection and scroll-activation are very related. TL;DR there are 3 reasons to lock an element
1 UX is that this is not in the document at all
2 UX is that this is perfectly normal document content but JS is taking control for performance reasons, scroll and select both activate this content
3 new UX, invisible content that is findable, accessible, not scroll or select activatable

currently we only allow expressing 1 and something in-between 2 and 3. I think we probably want to be able to express all 3 distinctly, the question is whether we do that by making other primitives available or by directly expressing them (if we're sure they're the only combinations that make sense then maybe that's OK).

**Comment by chrishtr** [comment]
One option to consider is whether activation on scroll should occur relative to the scrolling containing-block ancestor of the locked element, rather than the root viewport.

This has the advantage of making it easier to optimize the code that determines intersection, if the only change to DOM state was a scroll offset. Also, if the developer desires to do root viewport-relative activation, they could also lock the scrolling element itself.

On the other hand, it has the disadvantage of needing invalidation when the scrolling element changes, defining what it means to be a scrolling container (maybe just as simple as "has overflow:scroll"), and being less intuitively clear than "intersects the viewport"

**Comment by chrishtr** [comment]
@szager-chromium

**Comment by fergald** [comment]
> One option to consider is whether activation on scroll should occur relative to the scrolling containing-block ancestor of the locked element, rather than the root viewport.

I think this can be made to work, as you say by locking the outer scrolling container(s) but I feel like it's just pushing a task out of the rendering engine onto the developer and that pretty much every developer will have to take care of it. Questions:
- Is there any real use-case for activate on scroll where you don't want to intersect the visible viewport or would everyone just go ahead and implement that in script?
- is the nested scroller case rare enough that offering the single-layer primitive covers a massive number of developers and it's only a small fraction who need to implement the nested version, thus justifying keeping the complexity out of the browser?
- can we just say "the frameworks will take care of the complexity"?
- can we provide a LAPI that makes it trivial for those who need it (something less than virtual-scroller)

**Comment by vmpstr** [comment]
Should we still be issuing beforeactivate event if we activate based on viewport intersections?

**Comment by chrishtr** [comment]
@fergald I agree with these comments. After discussing with @szager-chromium, I thought some more about it and am also less sure that the proposed restriction would really make it so much easier for the browser to implement.

And it doesn't seem *that* much harder to do the same thing as what the developer might do to chain scrollers.

**Comment by chrishtr** [comment]
> Should we still be issuing beforeactivate event if we activate based on viewport intersections?

I think it would be inconsistent not to.

**Comment by vmpstr** [comment]
Based on a discussion yesterday, it seems hard to have a scroller with many elements perform well while observing each element. There is hope that we can improve the performance in certain narrow cases (ie scroll changes but no layout occurs), but under activation these cases might not apply pretty frequently. That is, if we activate then we are likely to dirty layout so then we would fall back to a "slow" path in the intersection observer.

I think we need a more conservative approach. Specifically, **I propose having the ability to activate on scroll be an opt-in feature via a rendersubtree token.**  I don't have a good name at the moment, but essentially something like `activateVisibility` which would activate when visible. In the absence of the token, we would only activate under the rest of the algorithms (find-in-page, focus navigation, selection, etc). 

This, coupled with #80, would mean that to have "fully activatable" scenario, one would only have to specify this one token. 

However, we need to figure out what it would mean if the developer specifies an out-out from activation (ie `static` or whatever the keyword would be) and `activateVisibility`. In other words, it would be an awkward scenario where we only activate visibility and not the rest of the algorithms.

I think we can figure all of this out, as we should. All in all though, I think having default activatability with visibility activation is somewhat intractable at the moment.

**Comment by chrishtr** [comment]
I think the scroll activation should probably be the default, to make it easier on developers..

**Comment by rakina** [comment]
Yeah maybe it's ok to have scroll activate by default to make it easily
usable. How about something like "ignore-intersection" for just scrolling
and "ignore-activation" for everything? That allows more ignore-* in the
future I guess should we decide to have more control on activation

**Comment by vmpstr** [comment]
That makes sense! So then we would have default activate and a soft opt-out from the visibility activation and a hard opt-out from all activation. Any thoughts about naming? Maybe instead of "ignore", it's "skip"? Ie `skip-visibility-activation` and `skip-activation`, where the latter implies the former

**Comment by rakina** [comment]
> That makes sense! So then we would have default activate and a soft opt-out from the visibility activation and a hard opt-out from all activation. Any thoughts about naming? Maybe instead of "ignore", it's "skip"? Ie `skip-visibility-activation` and `skip-activation`, where the latter implies the former

I don't have a strong preference regarding "skip" and "ignore", but "visibility" sounds kinda weird because we already use "invisible"? - maybe "intersection" is clearer?

**Comment by vmpstr** [comment]
I don't really like intersection since it's not immediately clear intersection of what with what. How about we meet in the middle and say skip-viewport-activation? That way it kind of captures both visibility and intersection (with viewport)?

**Comment by vmpstr** [comment]
this came up at the virtual scroller sync up:

how about we define some classes of activation and have flags to control whether we activate or not. Specifically, maybe we should be putting tab navigation and selection into the same category as visibility activation, since cases that typically want to disable visibility activation also want to disable those.

The litmus test here is whether below the fold item can be activated with just the mouse or keyboard press (not including find in page or plugins that might use scroll into view and the like).. if so, it's as if it's "Dom content that is being optimized" as opposed to being actively hidden for a tab UI or collapsed section UI. 

of course virtual scroller that wants to control its own visibility intersections is kind of stuck in the middle, mostly wanting tab and selection activation, but not wanting viewport activation. maybe that's ok though and we can pick one or the other.
