### ISSUE TITLE
Spec: if containment can't apply then s-v has no effect (e.g. display: contents)

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#81]
I don't think we can reasonably expect to lock a display: contents element, since it has no box for which children can be skipped. That being said, in the imperative version we've relied on promise rejection or displayLock.locked value to figure out whether we're actually locked.

What should we do in the declarative version? Should we just clear the rendersubtree attribute? Or do nothing?

/cc @chrishtr @rakina

**Comment by chrishtr** [comment]
We should reconsider whether `display:contents` can be supported. Or at least, the following use-case needs to be handled somehow, and `display:contents` might fit the bill, since `display:contents` elements don't have boxes. Another option could be adding a new mode to `rendersubtree` that removes the root element from layout.

Right now, `rendersubtree` is not a drop-in replacement for `display:none`. Both Wikipedia and AMP use `display:none` as the way of representing content not currently displayed in a collapsed section.

Consider:
```
<div id=content style="display:none">
  My display-none'd content content
</div>
```

being replaced with:

```
<div id=content rendersubtree="invisible skip-viewport-activation">
  My rendersubtree'd content
</div>
```

With this approach, they have to deal with issues like how to make the  element not affect surrounding layout (*), and also somehow fixing other APIs like IntersectionObserver when observing `#content`.

AMP in particular encountered the IntersectionObserver issue, since `#content` now has a box and participates in layout.

(*) Two approaches:
```
{
  display: block;
  width: 100%;
  height: 0px !important;
  margin: 0px;
  border: 0px hidden;
  padding: 0;
  opacity: 0;
}
```

and

```
{ 
  position: absolute;
  left: -99999px;
  right: -99999px;
}
```

**Comment by chrishtr** [comment]
Of course, there is no way to apply style, layout or size containment to an element which has no layout, because it can't be a containing block...

**Comment by chrishtr** [comment]
`display:contents` won't work. The reason is that the whole API's performance characteristics rely on the root element with `rendersubtree` being in the stacking and containing block chain of all descendants, for performance reasons `display:contents` elements can't be that.

For `IntersectionObserver`, the problem can be solved with either of these approaches:
* Use a second div below `#content` that is observed.
* Don't call observe() on the observer until the rendersubtreeactivation event runs, and only call unobserve() when re-locking.

**Comment by vmpstr** [comment]
> `display:contents` won't work. The reason is that the whole API's performance characteristics rely on the root element with `rendersubtree` being in the stacking and containing block chain of all descendants, for performance reasons. `display:contents` elements can't be that.

I agree with this. It seems to be a bad match to use rendersubtree with display contents, exactly because display contents is a grouping type of element that propagates its children to its parent, whereas rendersubtree really wants to control the rendering of its children. These seem incompatible.

We should still consider what we write in a spec about this. There needs to be some explicit behavior (even if that behavior is "do nothing"). It'd be nice to be able to surface some sort of a warning or error, but we currently don't have any avenues for that. We could consider adding another event like rendersubtreeerror or something along those lines to be able to inform the developer that something has gone wrong.

**Comment by vmpstr** [comment]
Need to spec the fact that if required containment doesn't apply, then subtree-visibility has no effect.
