### ISSUE TITLE
Should navigation through tabs be treated like viewport intersection?

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#87]
A question was raised today in discussion with the AMP team:

Should tabbing between focusable elements be treated the same as a find-in-page for activation? It seems weird to open up collapsed sections on pressing tab.

If instead we grouped it with viewport intersection, under the `skip-viewport-activation` keyword, that would resolve this point. Is there a use-case for the opposite?

**Comment by fergald** [comment]
I don't think grouping it under `skip-viewport-activation` would be the
right thing to do. I think we should either expose each possibility
individually or define some higher level semantic groups that combine them
(or possibly do that later when we know what the commonly used combinations
are)

**Comment by rakina** [comment]
Yeah, it might be a bit presumptive to combine the activations together - some people might not want their collapsed sections to be findable, but some others might want that, etc. Since we are doing an origin trial anyways, maybe it's worth it to expose a way for users to allow/disallow certain types of activation and see how people are using it?

**Comment by vmpstr** [comment]
For reference, this is the list (as far as I know):

* find-in-page
* viewport intersection
* scrollIntoView()
* accessibility
* anchor links
* tab order
* selection

**Comment by vmpstr** [comment]
In no particular order, and ignoring virtual-scroller for just a second, I think it makes sense to me that:

* viewport activation and tab order are in the same conceptual area. That is, if you can tab into it, then when it's in the viewport it should also be visible since tabbing into something vs clicking into it when it's visible is two ways to accomplish the same thing.

* Same thing can be said about viewport and selection: if I can ctrl-a select something that is off screen, then when it's on screen I should be able to see it and select it with my mouse. I don't see how allowing one and preventing the other is a reasonable use case (maybe I'm missing something).

* I would argue focus() is the same as tab order, but since it's script controlled that one is a weaker case. There could be reasonable use cases to allow this but not allow tab order to activate.

* find-in-page has a specific case of searchable collapsed items that does not fit into viewport model, so this has to be distinct.

* scrollIntoView() is again a script action, so there may be reasonable use cases that only allow this activation on script and nothing else.

* anchor links seem half way between scrollIntoView and scrolling activation, since it could be a <a> tag that the developer put, or it could be an explicit url that the user typed in, so I'm not sure where that fits.

**Comment by chrishtr** [comment]
This is a great breakdown.

I agree that conceptually it doesn't make a lot of sense to me that tab order would be different than some other way of bringing content onto the screen.

The main counter argument, I believe, is that having internal IntersectionObservers and doing it on scroll may interfere with optimizations implemented by a virtual scroller.  However, I don't think we are totally sure about that.

Also, secondary point: I think an anchor link navigation seems like find-in-page. Seems weird to anchor link navigate to a thing and not show it.

Therefore I suggest we batch everything except anchor link navigation and find-in-page into "viewport" activation.

**Comment by chrishtr** [comment]
Precise proposal (small change from my previous comment):

Two groups: Viewport activation, Full activation.

find-in-page: Full activation
viewport intersection on scroll or due to layout change: Viewport activation
scrollIntoView(): Full activation
accessibility: Full activation
anchor links: Full activation
tab order: Viewport activation
selection: Viewport activation
focus(): Viewport activation

**Comment by chrishtr** [comment]
Reasoning for scrollIntoView() and focus() causing Full activation: seems very weird for script to call them but not actually want an activation.
